### PR TITLE
Master

### PR DESCRIPTION
**Pull request by Ingvix**

### CODE REVIEW

**Comment by hoelzro** [comment]
Thanks for the contribution - I'll probably be able to look at this tomorrow night!

**Comment by Ingvix** [comment]
Also made it so that the cover board is set up on launch with the timer just in case one doesn't go to the app when launched.

**Comment by hoelzro** [comment]
Thanks again - merged!  @Ingvix Do you think you'll have more improvements coming soon?  I ask because I'm wondering if I should push a new version to the store or wait.

**Comment by Ingvix** [comment]
I'm not sure how soon. I'm currently trying to implement a drag-to-cell feature so you can drag the value from the button to cell and there's again some new stuff for me to learn so it might take a while or not. I think it's quite safe to publish the current version as I don't think there's any minor stuff that should be fixed for now.

**Pull request merged**
