### PR TITLE
Bringing back support for tablet and introducing drag and drop

### PR DESCRIPTION
**Pull request by Ingvix**

### CODE REVIEW

**Comment by Ingvix** [comment]
Though now I wonder if it'd be better to use the SQL-database to save the settings like it's used with the board state. Then it would use only one saving method for everything but I'm not too familiar with it to say if it's good for saving simple bools. 

I'm currently working on the "Pencil In"-system which is almost ready in the frontend but I need to figure out how do the SQL-database work and how to save the pencil values there.

**Comment by hoelzro** [comment]
Thanks for the contribution @Ingvix!  I'll probably look at this tonight. If my testing doesn't encounter any problems, would you like me to release this to the store, or should I wait for further patches from you?

**Comment by Ingvix** [comment]
No new contribution coming too soon so you can release it.

**Comment by hoelzro** [comment]
Looks good to me @Ingvix! Thanks again for the contribution!

**Pull request merged**
