### PR TITLE
A lot of stuff improved

### PR DESCRIPTION
**Pull request by Ingvix**
- Feature to reset current game
- Support for landscape orientation
- Better UI support for a lot of devices, including tablets
- Cover board shows current game and is a bit larger
- Not sure if I forgot to mention something

I intend to try to add game timer feature next.

### CODE REVIEW

**Comment by Ingvix** [comment]
Also in-game functions moved to Pushupmenu instead of them all being in Pulldownmenu. Remorse timers added to game resetting and new game if current game is not over.

**Comment by hoelzro** [comment]
I just tried this - it looks and works great!  Thanks for sticking it out and contributing!

If you decide to contribute again in the future, would you mind breaking up your work into smaller commits?  It would make it much easier to review!

**Comment by Ingvix** [comment]
Yes, sorry about that. I'm still learning github and didn't realize it could and should be done like that. I'll try to commit them in smaller packages in the future.

Would you mind if I shared the app through OpenRepos to get some feedback and maybe new ideas?

**Comment by hoelzro** [comment]
Sure, go for it!  I also published your changes to the Jolla store as a new release!

**Pull request merged**
